### ISSUE TITLE
CSP Violation with unsafe-eval in json-logic-engine

### ISSUE THREAD

**Issue by jrpedrianes** [TotalTechGeek/handlebars-jle#1]
Hi,

I’m having trouble with the Content Security Policy (CSP) when using this library. My CSP doesn’t allow unsafe-eval, and even though the README says this library doesn’t use functions that cause CSP errors, the issue comes from its dependency on json-logic-engine.

After checking, I found that json-logic-engine uses `eval`on [this line](https://github.com/TotalTechGeek/json-logic-engine/blob/master/compiler.js#L302), which triggers the CSP error.

Could you let me know:

* Is this something missed in the documentation, or is it intentional?
* Is there a way to avoid this CSP issue while still using handlebars-jle and its dependency?

Thanks for your help! Let me know if you need more details.

Best regards,

**Comment by TotalTechGeek** [comment]
Hey @jrpedrianes, 

The JSON-Logic-Engine module, as well as this one, supports both a compiled mode and an interpreted mode.

For the purposes of this module, instead of using `compile`, you need to use `interpreted` (sorry, I need to update the docs to make this clear).

The signature is the same as compiled; `interpreted(script: string, options)`

**Comment by TotalTechGeek** [comment]
Some further info: JLE's interpreter is able to use a WeakMap against the AST to cache an execution plan; which creates bindings between methods via closures so that it doesn't need to traverse the instructions each time. 

This allows the JIT to optimize things that it otherwise wouldn't be able to if I was crawling the AST. 

`interpreted` in Handlebars-JLE creates the AST and binds it to the `engine.run` function, making sure it can reuse that execution plan if the method is called again.

This leads to it having better performance compared to the Visitor approach used by the Kibana Fork of Handlebars.

It also seems to outperform Handlebar's compiler in most cases as well, which is a bit interesting.

**Comment by TotalTechGeek** [comment]
Going to close the issue for now; if you have any trouble, don't hesitate to re-open or file a new one :)

**Comment by jrpedrianes** [comment]
Hello @TotalTechGeek, 

Over the weekend, I didn’t have access to my laptop and couldn’t test your suggestion.

I’ve just had the chance to try it out, and it works like a charm 🎉.

I really appreciate your help and the time you took to provide these suggestions. 

Thanks!!!
